Improve the regression testing with GitHub Actions
drand/drand pull request #1144
Opened 2023-01-30 15:38 UTC by dlsniper

This PR addresses the following issues:
- The regression tests were running `make build .` instead of `make build`
- The regression tests were not using the unchained network, nor the new unchained on g1 network
- The regression tests were not using GitHub Actions matrix style to compose the regression tests

2023-01-30 15:41 UTC, AnomalRoil submitted a review, later dismissed

2023-01-30 15:42 UTC, CluEleSsUK approved these changes

2023-01-30 20:39 UTC, dlsniper commented
One problem with the matrix approach is that failing tests automatically cancel all tests in that matrix.
This shouldn't be a problem once we fix all the flaky tests.

2023-01-31 20:58 UTC, AnomalRoil requested changes

2023-01-31 20:58 UTC, AnomalRoil commented on .github/workflows/regression.yml
>          id: regression-bolt
I guess these bolt mentions might be replaced with variables now?

2023-01-31 20:58 UTC, AnomalRoil commented on .github/workflows/tests.yaml
>            DRAND_TEST_LOGS: "${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}"
Should we also add `CI: "true"` to it here?
The CI env variable is making some timeout/sleeps slower in our test suite, which can help with running them on slow machines

2023-02-01 13:54 UTC, AnomalRoil approved these changes

2023-02-01 13:56 UTC, merged