Send group size and threshold metrics when DKG/reshare starts
drand/drand pull request #999
Opened 2022-05-10 14:13 UTC by mcamou

@AnomalRoil @willscott I *think* I have set these up correctly, please do a sanity check whether this is the correct place to send the metrics when the DKG/reshare starts

2022-05-10 15:59 UTC, mcamou commented on core/drand_beacon_control.go
> +	metrics.GroupThreshold.WithLabelValues(beaconID).Set(float64(in.Info.Threshold))
good call, thanks.

2022-05-11 14:43 UTC, AnomalRoil requested changes

2022-05-11 14:43 UTC, AnomalRoil commented on core/drand_beacon_control.go
> +	metrics.GroupThreshold.WithLabelValues(bp.getBeaconID()).Set(float64(in.Info.Threshold))
This `setupAutomaticResharing` function is never called by the leader. The other two locations are enough.

2022-05-11 15:50 UTC, AnomalRoil approved these changes
LGTM now

2022-05-11 15:57 UTC, merged